In [2]:
import numpy as np
import pandas as pd
from pathlib import Path

In [2]:
PUPIL_ROOT = Path(r"C:\Users\cdd\Documents\Uni\Special_course\pupil_processed_clara")
EEG_ROOT   = Path(r"C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_processed2")
SUBJECTS   = [f"sub-{sid:03d}" for sid in range(32, 99) if sid not in (37,66,94)]

In [3]:
from pathlib import Path

# Base directory
base_dir = Path(r"C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_processed2")

missing = []

# Iterate over all subdirectories matching "sub-*"
for sub in base_dir.glob("sub-*"):
    memory_dir = sub / "memory" / "05"
    target = memory_dir / "epoch_035.csv"

    if not target.exists():
        missing.append(str(sub.name))

if missing:
    print("The following subjects are missing epoch_035.csv in their memory folder:")
    for subj in missing:
        print(f"  • {subj}")
else:
    print("All memory folders contain epoch_035.csv.")

All memory folders contain epoch_035.csv.

subject 32 and 61 should not have them (at least they dont for pupillometry). This is a bit weird, for now i am going to remove them from the analysis. Subject 42, indeed has extra trials in pupillometry and EEG, we keep it.
Now lets see how we skip the rejected trials in pupillometry from EEG too.

In [4]:
"""
trial_order_from_fif.py  —  robustly recover trial order
========================================================
Problem fixed: when triggers are stored as **annotations**, the numeric event
codes get remapped to arbitrary indices by `mne.events_from_annotations`, so our
previous parser never saw the real codes.  The new version:

1. **Inspects `raw.annotations` directly.**  Each annotation’s *description* is
   the 7-digit trigger (e.g. "6001051").
2. Falls back to the stim channel if annotations are absent.
3. Keeps only triggers whose *position field* is `01` (trial start).
4. Outputs `trial_order.tsv` with
   `subject  condition  load  trial_idx` (chronological `trial_idx` per subject).

Run:
```bash
python trial_order_from_fif.py
```

Dependencies: `mne >= 1.0`, `pandas`, `pathlib` (built-in).
"""

from pathlib import Path
from typing import List
import pandas as pd
import mne

# ─────────────────────────────────────────────────────────────────────────────
BASE = Path(r"C:\Users\cdd\Documents\Uni\Special_course")
EEG_FIF_ROOT = BASE / "code" / "Special_course" / "EEG_amica_processed"
OUTFILE      = BASE / "trial_order_eeg.tsv"
# ─────────────────────────────────────────────────────────────────────────────


def decode_event_code(code_str: str):
    """Decode *code_str* (7-digit string) → (condition, load, position)."""
    if len(code_str) > 8  or not code_str.isdigit():
        print(f"{code_str} is not a 7-digit or 6 number")
        raise ValueError("code_str must be a number")
        

    s = code_str
    cond_code, pos_code, len_code = s[:2], s[2:4], s[4:6]

    condition = {"50": "control", "60": "memory"}.get(cond_code)
    if condition is None:
        raise ValueError("condition code not 50/60")

    load = {"05": 5, "09": 9, "13": 13}.get(len_code)
    if load is None:
        raise ValueError("unexpected seq length")

    position = int(pos_code)
    return condition, load, position


def extract_trials_from_annotations(raw, subject: str) -> List[tuple]:
    rows = []
    trial_idx = 0
    for onset, duration, desc in zip(raw.annotations.onset,
                                     raw.annotations.duration,
                                     raw.annotations.description):
        try:
            cond, load, pos = decode_event_code(desc)
        except ValueError:
            continue
        if pos != 1:
            continue
        rows.append((subject, cond, load, trial_idx))
        trial_idx += 1
    return rows


def extract_trials_from_stim(raw, subject: str) -> List[tuple]:
    rows = []
    trial_idx = 0
    events = mne.find_events(raw, verbose="ERROR")
    for _, _, code in events:
        try:
            cond, load, pos = decode_event_code(str(code))
        except ValueError:
            continue
        if pos != 1:
            continue
        rows.append((subject, cond, load, trial_idx))
        trial_idx += 1
    return rows


def trial_order_for_subject(fif_path: Path) -> pd.DataFrame:
    subj = fif_path.parent.name
    raw = mne.io.read_raw_fif(fif_path, preload=False, verbose="ERROR")

    rows = (extract_trials_from_annotations(raw, subj)
            if raw.annotations else [])
    if not rows:
        rows = extract_trials_from_stim(raw, subj)
    if not rows:
        raise RuntimeError("no trial-start events found")

    return pd.DataFrame(rows, columns=["subject", "condition", "load", "trial_idx"])


def build_table() -> pd.DataFrame:
    dfs = []
    for fif in sorted(EEG_FIF_ROOT.glob("sub-*/*.fif")):
        try:
            dfs.append(trial_order_for_subject(fif))
        except Exception as e:
            print(f"‼️  {fif.name}: {e}")
    if not dfs:
        raise RuntimeError("no subjects processed successfully")
    return pd.concat(dfs, ignore_index=True)


def main():
    table = build_table()
    table.to_csv(OUTFILE, sep="\t", index=False)
    print(f"Wrote trial order for {table.subject.nunique()} subjects → {OUTFILE}")


if __name__ == "__main__":
    main()

boundary is not a 7-digit or 6 number
boundary is not a 7-digit or 6 number
boundary is not a 7-digit or 6 number
boundary is not a 7-digit or 6 number
boundary is not a 7-digit or 6 number
boundary is not a 7-digit or 6 number
boundary is not a 7-digit or 6 number
boundary is not a 7-digit or 6 number
boundary is not a 7-digit or 6 number
boundary is not a 7-digit or 6 number
boundary is not a 7-digit or 6 number
boundary is not a 7-digit or 6 number
boundary is not a 7-digit or 6 number
boundary is not a 7-digit or 6 number
boundary is not a 7-digit or 6 number
boundary is not a 7-digit or 6 number
boundary is not a 7-digit or 6 number
boundary is not a 7-digit or 6 number
boundary is not a 7-digit or 6 number
boundary is not a 7-digit or 6 number
boundary is not a 7-digit or 6 number
boundary is not a 7-digit or 6 number
boundary is not a 7-digit or 6 number
boundary is not a 7-digit or 6 number
boundary is not a 7-digit or 6 number
boundary is not a 7-digit or 6 number
boundary is not a 7-digit or 6 number
boundary is not a 7-digit or 6 number
boundary is not a 7-digit or 6 number
boundary is not a 7-digit or 6 number
boundary is not a 7-digit or 6 number
boundary is not a 7-digit or 6 number
boundary is not a 7-digit or 6 number
boundary is not a 7-digit or 6 number
boundary is not a 7-digit or 6 number
boundary is not a 7-digit or 6 number
boundary is not a 7-digit or 6 number
boundary is not a 7-digit or 6 number
boundary is not a 7-digit or 6 number
boundary is not a 7-digit or 6 number
boundary is not a 7-digit or 6 number
boundary is not a 7-digit or 6 number
boundary is not a 7-digit or 6 number
boundary is not a 7-digit or 6 number
boundary is not a 7-digit or 6 number
boundary is not a 7-digit or 6 number
boundary is not a 7-digit or 6 number
boundary is not a 7-digit or 6 number
boundary is not a 7-digit or 6 number
boundary is not a 7-digit or 6 number
boundary is not a 7-digit or 6 number
boundary is not a 7-digit or 6 number
boundary is not a 7-digit or 6 number
boundary is not a 7-digit or 6 number
boundary is not a 7-digit or 6 number
boundary is not a 7-digit or 6 number
boundary is not a 7-digit or 6 number
boundary is not a 7-digit or 6 number
boundary is not a 7-digit or 6 number
boundary is not a 7-digit or 6 number
boundary is not a 7-digit or 6 number
boundary is not a 7-digit or 6 number
boundary is not a 7-digit or 6 number
boundary is not a 7-digit or 6 number
boundary is not a 7-digit or 6 number
boundary is not a 7-digit or 6 number
boundary is not a 7-digit or 6 number
boundary is not a 7-digit or 6 number
boundary is not a 7-digit or 6 number
boundary is not a 7-digit or 6 number
boundary is not a 7-digit or 6 number
boundary is not a 7-digit or 6 number
boundary is not a 7-digit or 6 number
boundary is not a 7-digit or 6 number
Wrote trial order for 63 subjects → C:\Users\cdd\Documents\Uni\Special_course\trial_order_eeg.tsv

In [7]:
# ───────────────────────────────────────────────────────────────────────────
BASE = Path(r"C:\Users\cdd\Documents\Uni\Special_course")
TSV_ROOT   = BASE / "ds003838-download"
OUTFILE    = BASE / "trial_order_pupil.tsv"
# ───────────────────────────────────────────────────────────────────────────


def decode_label(label: str):
    """Return (condition, load, position) parsed from a numeric *label* string."""
    if not label.isdigit() or len(label) < 6:
        raise ValueError("label isn’t a 6+/7‑digit number")

    cond_code = label[:2]
    position  = int(label[2:4])
    load_code = label[4:6]

    condition = {"50": "control", "60": "memory"}.get(cond_code)
    if condition is None:
        raise ValueError("unknown condition code")

    load = {"05": 5, "09": 9, "13": 13}.get(load_code)
    if load is None:
        raise ValueError("unexpected load code")

    return condition, load, position


def trial_order_for_subject(tsv_path: Path) -> pd.DataFrame:
    subject = tsv_path.parent.parent.name  # sub-XXX
    df      = pd.read_csv(tsv_path, sep="\t")

    rows = []
    trial_idx = 0

    for label in df["label"]:
        try:
            cond, load, pos = decode_label(str(label))
        except ValueError:
            continue
        if pos != 1:
            continue
        rows.append((subject, cond, load, trial_idx))
        trial_idx += 1

    if not rows:
        raise RuntimeError(f"no trial‑start codes found in {tsv_path}")

    return pd.DataFrame(rows, columns=["subject", "condition", "load", "trial_idx"])


def build_table():
    all_rows = []
    pattern = TSV_ROOT.glob("sub-*/pupil/*_task-memory_events.tsv")
    for tsv in sorted(pattern):
        try:
            all_rows.append(trial_order_for_subject(tsv))
        except Exception as e:
            print(f"‼️  {tsv.name}: {e}")
    if not all_rows:
        raise RuntimeError("no TSV files processed successfully")
    return pd.concat(all_rows, ignore_index=True)


if __name__ == "__main__":
    table = build_table()
    table.to_csv(OUTFILE, sep="\t", index=False)
    print(f"Wrote trial order for {table.subject.nunique()} subjects → {OUTFILE}")

Wrote trial order for 64 subjects → C:\Users\cdd\Documents\Uni\Special_course\trial_order_pupil.tsv

In [12]:
from pathlib import Path
import pandas as pd
import sys

# Base data directory
BASE = Path(r"C:\Users\cdd\Documents\Uni\Special_course")

EEG_ORDER_FILE  = BASE / "trial_order_eeg.tsv"
TSV_ORDER_FILE  = BASE / "trial_order_pupil.tsv"


def _fmt_sub(sub):
    """Return canonical subject string (e.g. 32 → sub-032)."""
    sub = str(sub)
    if sub.startswith("sub-"):
        return sub
    return f"sub-{int(sub):03d}"


def compare_trial_order(subject: str,
                        eeg_file: Path = EEG_ORDER_FILE,
                        tsv_file: Path = TSV_ORDER_FILE,
                        verbose: bool = True) -> bool:
    """Return True if the two trial‑order tables match exactly for *subject*.

    *Matches* means:
    1. Both tables contain the same number of trials for this subject.
    2. After sorting by `trial_idx`, every corresponding row shares the same
       `(condition, load)`.
    """
    sub = _fmt_sub(subject)

    try:
        df_eeg = pd.read_csv(eeg_file, sep="\t")
        df_tsv = pd.read_csv(tsv_file, sep="\t")
    except Exception as e:
        raise RuntimeError(f"Error loading order files: {e}")

    e1 = df_eeg[df_eeg["subject"] == sub].sort_values("trial_idx")
    e2 = df_tsv[df_tsv["subject"] == sub].sort_values("trial_idx")

    if e1.empty or e2.empty:
        if verbose:
            print(f"‼️  Subject {sub} not found in one of the tables.")
        return False

    if len(e1) != len(e2):
        if verbose:
            print(f"❌ Trial counts differ — EEG: {len(e1)}, TSV: {len(e2)}")
        return False

    mism = (e1[["condition", "load"]].reset_index(drop=True) !=
            e2[["condition", "load"]].reset_index(drop=True)).any(axis=1)

    if mism.any():
        if verbose:
            bad_rows = mism[mism].index.tolist()[:5]  # show up to 5 mismatches
            print(f"❌ Order mismatch at trial indices {bad_rows} (showing up to 5).")
        return False

    if verbose:
        print(f"✅ Trial order matches for {sub} (n={len(e1)} trials).")
    return True


# Compare trial order for all subjects from 032 to 098
mismatches = []
matches = []

for sid in range(32, 99):
    # Skip known missing subjects based on cell 3
    if sid in [37, 66, 94]:
        continue
        
    subject = f"sub-{sid:03d}"
    # First check without verbose output
    if compare_trial_order(subject, verbose=False):
        matches.append(subject)
    else:
        # Run again with verbose=True to see the mismatch details
        compare_trial_order(subject, verbose=True)
        mismatches.append(subject)

print(f"\nSummary:")
print(f"Matches: {len(matches)} subjects")
print(f"Mismatches: {len(mismatches)} subjects")
if mismatches:
    print(f"Mismatched subjects: {', '.join(mismatches)}")

❌ Trial counts differ — EEG: 162, TSV: 144
❌ Trial counts differ — EEG: 162, TSV: 137
‼️  Subject sub-096 not found in one of the tables.

Summary:
Matches: 61 subjects
Mismatches: 3 subjects
Mismatched subjects: sub-032, sub-061, sub-096

In [29]:
from __future__ import annotations
from pathlib import Path
import argparse
import pandas as pd
from typing import Dict, Tuple, List

# ---------------------------------------------------------------------------
#  Epoch‑range specification  (start, end) are **inclusive**
# ---------------------------------------------------------------------------
RANGES_DEFAULT: Dict[Tuple[str, int], Tuple[int, int]] = {
    ("memory", 5):   (0,   35),
    ("control", 5):  (36,  53),
    ("memory", 9):   (54,  89),
    ("control", 9):  (90,  107),
    ("memory", 13):  (108, 143),
    ("control", 13): (144, 161),
}

RANGES_SUB42: Dict[Tuple[str, int], Tuple[int, int]] = {
    ("memory", 5):   (0,   35),
    ("control", 5):  (36,  54),
    ("memory", 9):   (55,  90),
    ("control", 9):  (91,  109),
    ("memory", 13):  (110, 145),
    ("control", 13): (146, 164),
}

# ---------------------------------------------------------------------------
#  Core logic
# ---------------------------------------------------------------------------

def _build_counters(ranges: Dict[Tuple[str, int], Tuple[int, int]]):
    """Return mutable counters {key → next_epoch_int}."""
    return {k: v[0] for k, v in ranges.items()}


def _next_epoch(counters: Dict[Tuple[str, int], int], key: Tuple[str, int], ranges):
    start, end = ranges[key]
    cur = counters[key]
    if cur > end:
        raise ValueError(f"Out of epoch numbers for {key}; exceeded {end}.")
    counters[key] += 1
    return cur


def add_epoch_column(df: pd.DataFrame) -> pd.DataFrame:
    """Append `epoch_num` respecting per‑subject rules and return the new DF."""
    df = df.copy().sort_values(["subject", "trial_idx"])  # ensure order
    epoch_nums: List[int] = []

    for sub, sub_df in df.groupby("subject", sort=False):
        ranges = RANGES_SUB42 if sub == "sub-042" else RANGES_DEFAULT
        ctrs = _build_counters(ranges)
        for cond, load in zip(sub_df["condition"], sub_df["load"]):
            epoch_nums.append(_next_epoch(ctrs, (cond, int(load)), ranges))

    df["epoch_num"] = epoch_nums
    return df

def add_epoch_corrected_column(
        in_tsv: str | Path,
        out_tsv: str | Path | None = None,
) -> pd.DataFrame:
    """
    Load the TSV that already contains `epoch_num`, append a new
    column `epoch_corrected`, and (optionally) write it back.

    `epoch_corrected` is simply a sequential counter (00, 01, …)
    **inside every (subject, condition, load) folder**.
    """
    df = pd.read_csv(in_tsv, sep="\t")

    # Sequential index per folder
    df["epoch_corrected"] = (
        df.groupby(["subject", "condition", "load"])
          .cumcount()
          .map(lambda x: f"{x:02d}")          # zero-padded 2-digit string
    )

    # Save if the user provided an output path
    if out_tsv is not None:
        Path(out_tsv).parent.mkdir(parents=True, exist_ok=True)
        df.to_csv(out_tsv, sep="\t", index=False)

    return df
    

# ---------------------------------------------------------------------------
#  CLI entry‑point
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    in_path = r"C:\Users\cdd\Documents\Uni\Special_course\trial_order_eeg.tsv"
    out_path = r"C:\Users\cdd\Documents\Uni\Special_course\trial_order_eeg.tsv_with_epoch.tsv"

    df_in = pd.read_csv(in_path, sep="\t")
    df_out = add_epoch_column(df_in)
    df_out.to_csv(out_path, sep="\t", index=False)
    print(f"✅  Saved {len(df_out)} rows to {out_path}")

✅  Saved 10209 rows to C:\Users\cdd\Documents\Uni\Special_course\trial_order_eeg.tsv_with_epoch.tsv

In [30]:
add_epoch_corrected_column(out_path, out_path)

       subject condition  load  trial_idx  epoch_num epoch_corrected
0      sub-032   control    13          0        144              00
1      sub-032   control     5          1         36              00
2      sub-032   control     9          2         90              00
3      sub-032    memory     5          3          0              00
4      sub-032    memory     9          4         54              00
...        ...       ...   ...        ...        ...             ...
10204  sub-098    memory     9        157         89              35
10205  sub-098    memory     5        158         35              35
10206  sub-098   control     5        159         53              17
10207  sub-098   control    13        160        161              17
10208  sub-098   control     9        161        107              17

[10209 rows x 6 columns]

In [ ]:
# ----------------------------------------------------------------------
from pathlib import Path
from typing  import Union
import pandas as pd

PathLike = Union[str, Path]

SKIP_LOG = (
    r"C:\Users\cdd\Documents\Uni\Special_course\pupil_processed_clara"
    r"\trial_skip_log.tsv"
)

def add_epoch_corrected_skip_column(
        in_tsv : PathLike,                    # table that ALREADY has epoch_corrected
        out_tsv: PathLike | None = None,
        skip_log: PathLike = SKIP_LOG,
) -> pd.DataFrame:
    """
    • Copy `epoch_corrected` into `epoch_corrected_skip`.
    • Wherever (sub,cond,load,trial_idx) appears in the pupil skip-log,
      set that row to <NA>.
    • Keep counting 00, 01, 02 … only on the *kept* rows.

    That yields exactly: 00, 01, NA, 02, 03 … inside every folder.
    """
    # ---------------- 1. load the two tables ----------------
    df   = pd.read_csv(in_tsv,  sep="\t")
    skip = pd.read_csv(skip_log, sep="\t",
                       usecols=["subject","condition","load","trial_idx"])

    # ---------------- 2. normalise key columns --------------
    for col in ("subject", "condition"):
        df[col]   = df[col].astype(str).str.strip().str.lower()
        skip[col] = skip[col].astype(str).str.strip().str.lower()

    for col in ("load", "trial_idx"):
        df[col]   = df[col].astype(int)
        skip[col] = skip[col].astype(int)

    # -------- 3. build a fast lookup: {(sub,cond,load): {trial_idx,…}} ----
    skip_lookup: dict[tuple[str,str,int], set[int]] = {}
    for rec in skip.itertuples(index=False):
        key = (rec.subject, rec.condition, rec.load)
        skip_lookup.setdefault(key, set()).add(rec.trial_idx)

    # ---------------- 4. compute epoch_corrected_skip ---------
    def folder_logic(folder: pd.DataFrame) -> pd.Series:
        key        = (folder["subject"].iat[0],
                      folder["condition"].iat[0],
                      folder["load"].iat[0])
        bad_trials = skip_lookup.get(key, set())

        counter = 0
        out = []
        for tidx in folder["trial_idx"]:
            if tidx in bad_trials:
                out.append(pd.NA)
            else:
                out.append(f"{counter:02d}")
                counter += 1
        return pd.Series(out, index=folder.index)

    df["epoch_corrected_skip"] = (
        df.sort_values(["subject","condition","load","trial_idx"])
          .groupby(["subject","condition","load"], group_keys=False)
          .apply(folder_logic)
    )

    # --------------- 5. save / return -----------------------
    if out_tsv:
        Path(out_tsv).parent.mkdir(parents=True, exist_ok=True)
        df.to_csv(out_tsv, sep="\t", index=False)

    return df
# ----------------------------------------------------------------------

In [32]:
add_epoch_corrected_skip_column(
    r"C:\Users\cdd\Documents\Uni\Special_course\trial_order_eeg.tsv_with_epoch.tsv",
    r"C:\Users\cdd\Documents\Uni\Special_course\trial_order_eeg.tsv_with_epoch_skip.tsv"
)

C:\Users\cdd\AppData\Local\Temp\ipykernel_33620\3116280062.py:64: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df.sort_values(["subject","condition","load","trial_idx"])

,subject,condition,load,trial_idx,epoch_num,epoch_corrected,epoch_corrected_skip
0,sub-032,control,13,0,144,0,00
1,sub-032,control,5,1,36,0,00
2,sub-032,control,9,2,90,0,00
3,sub-032,memory,5,3,0,0,00
4,sub-032,memory,9,4,54,0,00
...,...,...,...,...,...,...,...
10204,sub-098,memory,9,157,89,35,12
10205,sub-098,memory,5,158,35,35,<NA>
10206,sub-098,control,5,159,53,17,<NA>
10207,sub-098,control,13,160,161,17,<NA>
10208,sub-098,control,9,161,107,17,<NA>

In [5]:
from pathlib import Path
import pandas as pd
import sys

# --------------------------------------------------------------------
# EDIT these three paths if your layout changes
MAPPING_TSV = (
    r"C:\Users\cdd\Documents\Uni\Special_course"
    r"\trial_order_eeg.tsv_with_epoch_skip.tsv"
)
EEG_ROOT = (
    r"C:\Users\cdd\Documents\Uni\Special_course\code\Special_course"
    r"\eeg_theta_processed2"
)
# --------------------------------------------------------------------

def rename_epochs(subject: str) -> None:
    """
    Rename files like
        …\sub-032\control\05\epoch_036.csv
    ▶︎ …\sub-032\control\05\epoch_001.csv
    where the mapping is read from the master TSV.

    Only rows for this subject are touched; other subjects stay intact.
    """
    subj = subject if subject.startswith("sub-") else f"sub-{int(subject):03d}"

    # --- read mapping for this subject only -------------------------
    cols = ["subject", "condition", "load", "trial_idx", "epoch_num"]
    df = (pd.read_csv(MAPPING_TSV, sep="\t", usecols=cols)
            .query("subject == @subj"))

    if df.empty:
        print(f"No rows for {subj} in mapping file.")
        return

    # --- go through every row and rename ----------------------------
    for row in df.itertuples(index=False):
        folder = (
            Path(EEG_ROOT) / row.subject / row.condition
            / f"{int(row.load):02d}"
        )
        old_f = folder / f"epoch_{int(row.epoch_num):03d}.csv"
        new_f = folder / f"trial_{int(row.trial_idx):03d}.csv"

        if not old_f.exists():
            print(f"⚠️  missing: {old_f}")
            continue

        if new_f.exists():
            print(f"⚠️  target already exists, skipping: {new_f}")
            continue

        old_f.rename(new_f)
        print(f"{old_f.name}  →  {new_f.name}")

    print(f"\nDone renaming files for {subj}.")

# Loop through all subjects from 033 to 099
for sid in range(32, 99):
    # Skip known missing subjects
    if sid in [37, 66, 94]:
        continue
    
    subject = f"sub-{sid:03d}"
    print(f"\nProcessing {subject}...")
    rename_epochs(subject)
    
print("\nAll subjects processed.")

Processing sub-032...
epoch_144.csv  →  trial_000.csv
epoch_036.csv  →  trial_001.csv
epoch_090.csv  →  trial_002.csv
epoch_000.csv  →  trial_003.csv
epoch_054.csv  →  trial_004.csv
epoch_108.csv  →  trial_005.csv
epoch_001.csv  →  trial_006.csv
epoch_055.csv  →  trial_007.csv
epoch_056.csv  →  trial_008.csv
epoch_002.csv  →  trial_009.csv
epoch_109.csv  →  trial_010.csv
epoch_110.csv  →  trial_011.csv
epoch_111.csv  →  trial_012.csv
epoch_057.csv  →  trial_013.csv
epoch_003.csv  →  trial_014.csv
epoch_091.csv  →  trial_015.csv
epoch_037.csv  →  trial_016.csv
epoch_145.csv  →  trial_017.csv
epoch_038.csv  →  trial_018.csv
epoch_092.csv  →  trial_019.csv
epoch_146.csv  →  trial_020.csv
epoch_058.csv  →  trial_021.csv
epoch_004.csv  →  trial_022.csv
epoch_112.csv  →  trial_023.csv
epoch_113.csv  →  trial_024.csv
epoch_114.csv  →  trial_025.csv
epoch_059.csv  →  trial_026.csv
epoch_115.csv  →  trial_027.csv
epoch_060.csv  →  trial_028.csv
epoch_005.csv  →  trial_029.csv
epoch_061.csv  →  trial_030.csv
epoch_006.csv  →  trial_031.csv
epoch_007.csv  →  trial_032.csv
epoch_147.csv  →  trial_033.csv
epoch_039.csv  →  trial_034.csv
epoch_093.csv  →  trial_035.csv
epoch_094.csv  →  trial_036.csv
epoch_040.csv  →  trial_037.csv
epoch_148.csv  →  trial_038.csv
epoch_062.csv  →  trial_039.csv
epoch_063.csv  →  trial_040.csv
epoch_064.csv  →  trial_041.csv
epoch_008.csv  →  trial_042.csv
epoch_116.csv  →  trial_043.csv
epoch_117.csv  →  trial_044.csv
epoch_009.csv  →  trial_045.csv
epoch_010.csv  →  trial_046.csv
epoch_011.csv  →  trial_047.csv
epoch_118.csv  →  trial_048.csv
epoch_065.csv  →  trial_049.csv
epoch_119.csv  →  trial_050.csv
epoch_095.csv  →  trial_051.csv
epoch_149.csv  →  trial_052.csv
epoch_041.csv  →  trial_053.csv
epoch_150.csv  →  trial_054.csv
epoch_096.csv  →  trial_055.csv
epoch_042.csv  →  trial_056.csv
epoch_120.csv  →  trial_057.csv
epoch_012.csv  →  trial_058.csv
epoch_066.csv  →  trial_059.csv
epoch_121.csv  →  trial_060.csv
epoch_067.csv  →  trial_061.csv
epoch_068.csv  →  trial_062.csv
epoch_069.csv  →  trial_063.csv
epoch_013.csv  →  trial_064.csv
epoch_122.csv  →  trial_065.csv
epoch_014.csv  →  trial_066.csv
epoch_123.csv  →  trial_067.csv
epoch_015.csv  →  trial_068.csv
epoch_043.csv  →  trial_069.csv
epoch_151.csv  →  trial_070.csv
epoch_097.csv  →  trial_071.csv
epoch_044.csv  →  trial_072.csv
epoch_098.csv  →  trial_073.csv
epoch_152.csv  →  trial_074.csv
epoch_016.csv  →  trial_075.csv
epoch_017.csv  →  trial_076.csv
epoch_124.csv  →  trial_077.csv
epoch_018.csv  →  trial_078.csv
epoch_070.csv  →  trial_079.csv
epoch_071.csv  →  trial_080.csv
epoch_072.csv  →  trial_081.csv
epoch_125.csv  →  trial_082.csv
epoch_126.csv  →  trial_083.csv
epoch_073.csv  →  trial_084.csv
epoch_019.csv  →  trial_085.csv
epoch_127.csv  →  trial_086.csv
epoch_153.csv  →  trial_087.csv
epoch_045.csv  →  trial_088.csv
epoch_099.csv  →  trial_089.csv
epoch_154.csv  →  trial_090.csv
epoch_100.csv  →  trial_091.csv
epoch_046.csv  →  trial_092.csv
epoch_128.csv  →  trial_093.csv
epoch_129.csv  →  trial_094.csv
epoch_020.csv  →  trial_095.csv
epoch_130.csv  →  trial_096.csv
epoch_021.csv  →  trial_097.csv
epoch_131.csv  →  trial_098.csv
epoch_074.csv  →  trial_099.csv
epoch_022.csv  →  trial_100.csv
epoch_075.csv  →  trial_101.csv
epoch_076.csv  →  trial_102.csv
epoch_023.csv  →  trial_103.csv
epoch_077.csv  →  trial_104.csv
epoch_155.csv  →  trial_105.csv
epoch_047.csv  →  trial_106.csv
epoch_101.csv  →  trial_107.csv
epoch_102.csv  →  trial_108.csv
epoch_048.csv  →  trial_109.csv
epoch_156.csv  →  trial_110.csv
epoch_132.csv  →  trial_111.csv
epoch_024.csv  →  trial_112.csv
epoch_025.csv  →  trial_113.csv
epoch_133.csv  →  trial_114.csv
epoch_078.csv  →  trial_115.csv
epoch_079.csv  →  trial_116.csv
epoch_026.csv  →  trial_117.csv
epoch_027.csv  →  trial_118.csv
epoch_080.csv  →  trial_119.csv
epoch_134.csv  →  trial_120.csv
epoch_135.csv  →  trial_121.csv
epoch_081.csv  →  trial_122.csv
epoch_049.csv  →  trial_123.csv
epoch_157.csv  →  trial_124.csv
epoch_103.csv  →  trial_125.csv
epoch_158.csv  →  trial_126.csv
epoch_050.csv  →  trial_127.csv
epoch_104.csv  →  trial_128.csv
epoch_028.csv  →  trial_129.csv
epoch_029.csv  →  trial_130.csv
epoch_136.csv  →  trial_131.csv
epoch_030.csv  →  trial_132.csv
epoch_082.csv  →  trial_133.csv
epoch_083.csv  →  trial_134.csv
epoch_137.csv  →  trial_135.csv
epoch_084.csv  →  trial_136.csv
epoch_031.csv  →  trial_137.csv
epoch_085.csv  →  trial_138.csv
epoch_138.csv  →  trial_139.csv
epoch_139.csv  →  trial_140.csv
epoch_159.csv  →  trial_141.csv
epoch_051.csv  →  trial_142.csv
epoch_105.csv  →  trial_143.csv
epoch_160.csv  →  trial_144.csv
epoch_106.csv  →  trial_145.csv
epoch_052.csv  →  trial_146.csv
epoch_140.csv  →  trial_147.csv
epoch_032.csv  →  trial_148.csv
epoch_086.csv  →  trial_149.csv
epoch_087.csv  →  trial_150.csv
epoch_141.csv  →  trial_151.csv
epoch_088.csv  →  trial_152.csv
epoch_033.csv  →  trial_153.csv
epoch_089.csv  →  trial_154.csv
epoch_034.csv  →  trial_155.csv
epoch_035.csv  →  trial_156.csv
epoch_142.csv  →  trial_157.csv
epoch_143.csv  →  trial_158.csv
epoch_053.csv  →  trial_159.csv
epoch_161.csv  →  trial_160.csv
epoch_107.csv  →  trial_161.csv

Done renaming files for sub-032.

Processing sub-033...
epoch_036.csv  →  trial_000.csv
epoch_144.csv  →  trial_001.csv
epoch_090.csv  →  trial_002.csv
epoch_108.csv  →  trial_003.csv
epoch_000.csv  →  trial_004.csv
epoch_054.csv  →  trial_005.csv
epoch_109.csv  →  trial_006.csv
epoch_110.csv  →  trial_007.csv
epoch_055.csv  →  trial_008.csv
epoch_056.csv  →  trial_009.csv
epoch_001.csv  →  trial_010.csv
epoch_057.csv  →  trial_011.csv
epoch_002.csv  →  trial_012.csv
epoch_003.csv  →  trial_013.csv
epoch_111.csv  →  trial_014.csv
epoch_091.csv  →  trial_015.csv
epoch_145.csv  →  trial_016.csv
epoch_037.csv  →  trial_017.csv
epoch_038.csv  →  trial_018.csv
epoch_146.csv  →  trial_019.csv
epoch_092.csv  →  trial_020.csv
epoch_112.csv  →  trial_021.csv
epoch_058.csv  →  trial_022.csv
epoch_059.csv  →  trial_023.csv
epoch_060.csv  →  trial_024.csv
epoch_061.csv  →  trial_025.csv
epoch_113.csv  →  trial_026.csv
epoch_004.csv  →  trial_027.csv
epoch_005.csv  →  trial_028.csv
epoch_006.csv  →  trial_029.csv
epoch_007.csv  →  trial_030.csv
epoch_114.csv  →  trial_031.csv
epoch_115.csv  →  trial_032.csv
epoch_093.csv  →  trial_033.csv
epoch_039.csv  →  trial_034.csv
epoch_147.csv  →  trial_035.csv
epoch_148.csv  →  trial_036.csv
epoch_040.csv  →  trial_037.csv
epoch_094.csv  →  trial_038.csv
epoch_116.csv  →  trial_039.csv
epoch_117.csv  →  trial_040.csv
epoch_062.csv  →  trial_041.csv
epoch_008.csv  →  trial_042.csv
epoch_063.csv  →  trial_043.csv
epoch_118.csv  →  trial_044.csv
epoch_064.csv  →  trial_045.csv
epoch_009.csv  →  trial_046.csv
epoch_010.csv  →  trial_047.csv
epoch_065.csv  →  trial_048.csv
epoch_119.csv  →  trial_049.csv
epoch_011.csv  →  trial_050.csv
epoch_149.csv  →  trial_051.csv
epoch_041.csv  →  trial_052.csv
epoch_095.csv  →  trial_053.csv
epoch_096.csv  →  trial_054.csv
epoch_150.csv  →  trial_055.csv
epoch_042.csv  →  trial_056.csv
epoch_120.csv  →  trial_057.csv
epoch_012.csv  →  trial_058.csv
epoch_013.csv  →  trial_059.csv
epoch_066.csv  →  trial_060.csv
epoch_014.csv  →  trial_061.csv
epoch_121.csv  →  trial_062.csv
epoch_122.csv  →  trial_063.csv
epoch_123.csv  →  trial_064.csv
epoch_067.csv  →  trial_065.csv
epoch_015.csv  →  trial_066.csv
epoch_068.csv  →  trial_067.csv
epoch_069.csv  →  trial_068.csv
epoch_043.csv  →  trial_069.csv
epoch_097.csv  →  trial_070.csv
epoch_151.csv  →  trial_071.csv
epoch_044.csv  →  trial_072.csv
epoch_152.csv  →  trial_073.csv
epoch_098.csv  →  trial_074.csv
epoch_070.csv  →  trial_075.csv
epoch_124.csv  →  trial_076.csv
epoch_016.csv  →  trial_077.csv
epoch_071.csv  →  trial_078.csv
epoch_017.csv  →  trial_079.csv
epoch_072.csv  →  trial_080.csv
epoch_125.csv  →  trial_081.csv
epoch_018.csv  →  trial_082.csv
epoch_126.csv  →  trial_083.csv
epoch_019.csv  →  trial_084.csv
epoch_127.csv  →  trial_085.csv
epoch_073.csv  →  trial_086.csv
epoch_099.csv  →  trial_087.csv
epoch_153.csv  →  trial_088.csv
epoch_045.csv  →  trial_089.csv
epoch_100.csv  →  trial_090.csv
epoch_046.csv  →  trial_091.csv
epoch_154.csv  →  trial_092.csv
epoch_128.csv  →  trial_093.csv
epoch_020.csv  →  trial_094.csv
epoch_021.csv  →  trial_095.csv
epoch_129.csv  →  trial_096.csv
epoch_074.csv  →  trial_097.csv
epoch_130.csv  →  trial_098.csv
epoch_131.csv  →  trial_099.csv
epoch_022.csv  →  trial_100.csv
epoch_075.csv  →  trial_101.csv
epoch_076.csv  →  trial_102.csv
epoch_023.csv  →  trial_103.csv
epoch_077.csv  →  trial_104.csv
epoch_155.csv  →  trial_105.csv
epoch_101.csv  →  trial_106.csv
epoch_047.csv  →  trial_107.csv
epoch_102.csv  →  trial_108.csv
epoch_156.csv  →  trial_109.csv
epoch_048.csv  →  trial_110.csv
epoch_078.csv  →  trial_111.csv
epoch_024.csv  →  trial_112.csv
epoch_132.csv  →  trial_113.csv
epoch_133.csv  →  trial_114.csv
epoch_134.csv  →  trial_115.csv
epoch_079.csv  →  trial_116.csv
epoch_080.csv  →  trial_117.csv
epoch_025.csv  →  trial_118.csv
epoch_081.csv  →  trial_119.csv
epoch_026.csv  →  trial_120.csv
epoch_027.csv  →  trial_121.csv
epoch_135.csv  →  trial_122.csv
epoch_103.csv  →  trial_123.csv
epoch_157.csv  →  trial_124.csv
epoch_049.csv  →  trial_125.csv
epoch_104.csv  →  trial_126.csv
epoch_158.csv  →  trial_127.csv
epoch_050.csv  →  trial_128.csv
epoch_082.csv  →  trial_129.csv
epoch_136.csv  →  trial_130.csv
epoch_083.csv  →  trial_131.csv
epoch_028.csv  →  trial_132.csv
epoch_084.csv  →  trial_133.csv
epoch_029.csv  →  trial_134.csv
epoch_137.csv  →  trial_135.csv
epoch_030.csv  →  trial_136.csv
epoch_031.csv  →  trial_137.csv
epoch_085.csv  →  trial_138.csv
epoch_138.csv  →  trial_139.csv
epoch_139.csv  →  trial_140.csv
epoch_159.csv  →  trial_141.csv
epoch_051.csv  →  trial_142.csv
epoch_105.csv  →  trial_143.csv
epoch_106.csv  →  trial_144.csv
epoch_052.csv  →  trial_145.csv
epoch_160.csv  →  trial_146.csv
epoch_086.csv  →  trial_147.csv
epoch_087.csv  →  trial_148.csv
epoch_140.csv  →  trial_149.csv
epoch_141.csv  →  trial_150.csv
epoch_088.csv  →  trial_151.csv
epoch_032.csv  →  trial_152.csv
epoch_033.csv  →  trial_153.csv
epoch_142.csv  →  trial_154.csv
epoch_034.csv  →  trial_155.csv
epoch_035.csv  →  trial_156.csv
epoch_143.csv  →  trial_157.csv
epoch_089.csv  →  trial_158.csv
epoch_107.csv  →  trial_159.csv
epoch_053.csv  →  trial_160.csv
epoch_161.csv  →  trial_161.csv

Done renaming files for sub-033.

Processing sub-034...
epoch_090.csv  →  trial_000.csv
epoch_144.csv  →  trial_001.csv
epoch_036.csv  →  trial_002.csv
epoch_108.csv  →  trial_003.csv
epoch_000.csv  →  trial_004.csv
epoch_054.csv  →  trial_005.csv
epoch_109.csv  →  trial_006.csv
epoch_001.csv  →  trial_007.csv
epoch_055.csv  →  trial_008.csv
epoch_002.csv  →  trial_009.csv
epoch_003.csv  →  trial_010.csv
epoch_110.csv  →  trial_011.csv
epoch_111.csv  →  trial_012.csv
epoch_056.csv  →  trial_013.csv
epoch_057.csv  →  trial_014.csv
epoch_145.csv  →  trial_015.csv
epoch_091.csv  →  trial_016.csv
epoch_037.csv  →  trial_017.csv
epoch_146.csv  →  trial_018.csv
epoch_092.csv  →  trial_019.csv
epoch_038.csv  →  trial_020.csv
epoch_058.csv  →  trial_021.csv
epoch_004.csv  →  trial_022.csv
epoch_059.csv  →  trial_023.csv
epoch_112.csv  →  trial_024.csv
epoch_060.csv  →  trial_025.csv
epoch_005.csv  →  trial_026.csv
epoch_113.csv  →  trial_027.csv
epoch_114.csv  →  trial_028.csv
epoch_006.csv  →  trial_029.csv
epoch_115.csv  →  trial_030.csv
epoch_007.csv  →  trial_031.csv
epoch_061.csv  →  trial_032.csv
epoch_147.csv  →  trial_033.csv
epoch_093.csv  →  trial_034.csv
epoch_039.csv  →  trial_035.csv
epoch_094.csv  →  trial_036.csv
epoch_148.csv  →  trial_037.csv
epoch_040.csv  →  trial_038.csv
epoch_062.csv  →  trial_039.csv
epoch_008.csv  →  trial_040.csv
epoch_063.csv  →  trial_041.csv
epoch_116.csv  →  trial_042.csv
epoch_009.csv  →  trial_043.csv
epoch_010.csv  →  trial_044.csv
epoch_011.csv  →  trial_045.csv
epoch_117.csv  →  trial_046.csv
epoch_118.csv  →  trial_047.csv
epoch_064.csv  →  trial_048.csv
epoch_119.csv  →  trial_049.csv
epoch_065.csv  →  trial_050.csv
epoch_149.csv  →  trial_051.csv
epoch_095.csv  →  trial_052.csv
epoch_041.csv  →  trial_053.csv
epoch_042.csv  →  trial_054.csv
epoch_096.csv  →  trial_055.csv
epoch_150.csv  →  trial_056.csv
epoch_066.csv  →  trial_057.csv
epoch_120.csv  →  trial_058.csv
epoch_012.csv  →  trial_059.csv
epoch_121.csv  →  trial_060.csv
epoch_122.csv  →  trial_061.csv
epoch_123.csv  →  trial_062.csv
epoch_013.csv  →  trial_063.csv
epoch_014.csv  →  trial_064.csv
epoch_067.csv  →  trial_065.csv
epoch_068.csv  →  trial_066.csv
epoch_069.csv  →  trial_067.csv
epoch_015.csv  →  trial_068.csv
epoch_151.csv  →  trial_069.csv
epoch_043.csv  →  trial_070.csv
epoch_097.csv  →  trial_071.csv
epoch_152.csv  →  trial_072.csv
epoch_044.csv  →  trial_073.csv
epoch_098.csv  →  trial_074.csv
epoch_016.csv  →  trial_075.csv
epoch_124.csv  →  trial_076.csv
epoch_070.csv  →  trial_077.csv
epoch_071.csv  →  trial_078.csv
epoch_017.csv  →  trial_079.csv
epoch_125.csv  →  trial_080.csv
epoch_126.csv  →  trial_081.csv
epoch_127.csv  →  trial_082.csv
epoch_072.csv  →  trial_083.csv
epoch_073.csv  →  trial_084.csv
epoch_018.csv  →  trial_085.csv
epoch_019.csv  →  trial_086.csv
epoch_099.csv  →  trial_087.csv
epoch_045.csv  →  trial_088.csv
epoch_153.csv  →  trial_089.csv
epoch_046.csv  →  trial_090.csv
epoch_154.csv  →  trial_091.csv
epoch_100.csv  →  trial_092.csv
epoch_074.csv  →  trial_093.csv
epoch_020.csv  →  trial_094.csv
epoch_021.csv  →  trial_095.csv
epoch_075.csv  →  trial_096.csv
epoch_128.csv  →  trial_097.csv
epoch_129.csv  →  trial_098.csv
epoch_022.csv  →  trial_099.csv
epoch_023.csv  →  trial_100.csv
epoch_076.csv  →  trial_101.csv
epoch_130.csv  →  trial_102.csv
epoch_077.csv  →  trial_103.csv
epoch_131.csv  →  trial_104.csv
epoch_047.csv  →  trial_105.csv
epoch_101.csv  →  trial_106.csv
epoch_155.csv  →  trial_107.csv
epoch_048.csv  →  trial_108.csv
epoch_156.csv  →  trial_109.csv
epoch_102.csv  →  trial_110.csv
epoch_024.csv  →  trial_111.csv
epoch_025.csv  →  trial_112.csv
epoch_132.csv  →  trial_113.csv
epoch_078.csv  →  trial_114.csv
epoch_133.csv  →  trial_115.csv
epoch_079.csv  →  trial_116.csv
epoch_134.csv  →  trial_117.csv
epoch_026.csv  →  trial_118.csv
epoch_027.csv  →  trial_119.csv
epoch_135.csv  →  trial_120.csv
epoch_080.csv  →  trial_121.csv
epoch_081.csv  →  trial_122.csv
epoch_049.csv  →  trial_123.csv
epoch_103.csv  →  trial_124.csv
epoch_157.csv  →  trial_125.csv
epoch_104.csv  →  trial_126.csv
epoch_050.csv  →  trial_127.csv
epoch_158.csv  →  trial_128.csv
epoch_028.csv  →  trial_129.csv
epoch_029.csv  →  trial_130.csv
epoch_136.csv  →  trial_131.csv
epoch_082.csv  →  trial_132.csv
epoch_137.csv  →  trial_133.csv
epoch_138.csv  →  trial_134.csv
epoch_083.csv  →  trial_135.csv
epoch_084.csv  →  trial_136.csv
epoch_139.csv  →  trial_137.csv
epoch_030.csv  →  trial_138.csv
epoch_031.csv  →  trial_139.csv
epoch_085.csv  →  trial_140.csv
epoch_159.csv  →  trial_141.csv
epoch_105.csv  →  trial_142.csv
epoch_051.csv  →  trial_143.csv
epoch_106.csv  →  trial_144.csv
epoch_160.csv  →  trial_145.csv
epoch_052.csv  →  trial_146.csv
epoch_086.csv  →  trial_147.csv
epoch_140.csv  →  trial_148.csv
epoch_032.csv  →  trial_149.csv
epoch_087.csv  →  trial_150.csv
epoch_033.csv  →  trial_151.csv
epoch_034.csv  →  trial_152.csv
epoch_088.csv  →  trial_153.csv
epoch_141.csv  →  trial_154.csv
epoch_142.csv  →  trial_155.csv
epoch_035.csv  →  trial_156.csv
epoch_089.csv  →  trial_157.csv
epoch_143.csv  →  trial_158.csv
epoch_161.csv  →  trial_159.csv
epoch_107.csv  →  trial_160.csv
epoch_053.csv  →  trial_161.csv

Done renaming files for sub-034.

Processing sub-035...
epoch_090.csv  →  trial_000.csv
epoch_144.csv  →  trial_001.csv
epoch_036.csv  →  trial_002.csv
epoch_000.csv  →  trial_003.csv
epoch_108.csv  →  trial_004.csv
epoch_054.csv  →  trial_005.csv
epoch_109.csv  →  trial_006.csv
epoch_055.csv  →  trial_007.csv
epoch_110.csv  →  trial_008.csv
epoch_001.csv  →  trial_009.csv
epoch_002.csv  →  trial_010.csv
epoch_056.csv  →  trial_011.csv
epoch_057.csv  →  trial_012.csv
epoch_111.csv  →  trial_013.csv
epoch_003.csv  →  trial_014.csv
epoch_145.csv  →  trial_015.csv
epoch_091.csv  →  trial_016.csv
epoch_037.csv  →  trial_017.csv
epoch_038.csv  →  trial_018.csv
epoch_146.csv  →  trial_019.csv
epoch_092.csv  →  trial_020.csv
epoch_004.csv  →  trial_021.csv
epoch_112.csv  →  trial_022.csv
epoch_005.csv  →  trial_023.csv
epoch_113.csv  →  trial_024.csv
epoch_058.csv  →  trial_025.csv
epoch_059.csv  →  trial_026.csv
epoch_006.csv  →  trial_027.csv
epoch_114.csv  →  trial_028.csv
epoch_115.csv  →  trial_029.csv
epoch_060.csv  →  trial_030.csv
epoch_061.csv  →  trial_031.csv
epoch_007.csv  →  trial_032.csv
epoch_093.csv  →  trial_033.csv
epoch_039.csv  →  trial_034.csv
epoch_147.csv  →  trial_035.csv
epoch_148.csv  →  trial_036.csv
epoch_094.csv  →  trial_037.csv
epoch_040.csv  →  trial_038.csv
epoch_116.csv  →  trial_039.csv
epoch_117.csv  →  trial_040.csv
epoch_008.csv  →  trial_041.csv
epoch_118.csv  →  trial_042.csv
epoch_009.csv  →  trial_043.csv
epoch_010.csv  →  trial_044.csv
epoch_062.csv  →  trial_045.csv
epoch_063.csv  →  trial_046.csv
epoch_119.csv  →  trial_047.csv
epoch_011.csv  →  trial_048.csv
epoch_064.csv  →  trial_049.csv
epoch_065.csv  →  trial_050.csv
epoch_149.csv  →  trial_051.csv
epoch_041.csv  →  trial_052.csv
epoch_095.csv  →  trial_053.csv
epoch_150.csv  →  trial_054.csv
epoch_096.csv  →  trial_055.csv
epoch_042.csv  →  trial_056.csv
epoch_120.csv  →  trial_057.csv
epoch_121.csv  →  trial_058.csv
epoch_066.csv  →  trial_059.csv
epoch_067.csv  →  trial_060.csv
epoch_012.csv  →  trial_061.csv
epoch_013.csv  →  trial_062.csv
epoch_014.csv  →  trial_063.csv
epoch_122.csv  →  trial_064.csv
epoch_068.csv  →  trial_065.csv
epoch_069.csv  →  trial_066.csv
epoch_123.csv  →  trial_067.csv
epoch_015.csv  →  trial_068.csv
epoch_043.csv  →  trial_069.csv
epoch_151.csv  →  trial_070.csv
epoch_097.csv  →  trial_071.csv
epoch_098.csv  →  trial_072.csv
epoch_044.csv  →  trial_073.csv
epoch_152.csv  →  trial_074.csv
epoch_016.csv  →  trial_075.csv
epoch_070.csv  →  trial_076.csv
epoch_124.csv  →  trial_077.csv
epoch_071.csv  →  trial_078.csv
epoch_017.csv  →  trial_079.csv
epoch_072.csv  →  trial_080.csv
epoch_018.csv  →  trial_081.csv
epoch_125.csv  →  trial_082.csv
epoch_019.csv  →  trial_083.csv
epoch_126.csv  →  trial_084.csv
epoch_073.csv  →  trial_085.csv
epoch_127.csv  →  trial_086.csv
epoch_099.csv  →  trial_087.csv
epoch_045.csv  →  trial_088.csv
epoch_153.csv  →  trial_089.csv
epoch_046.csv  →  trial_090.csv
epoch_154.csv  →  trial_091.csv
epoch_100.csv  →  trial_092.csv
epoch_128.csv  →  trial_093.csv
epoch_020.csv  →  trial_094.csv
epoch_021.csv  →  trial_095.csv
epoch_022.csv  →  trial_096.csv
epoch_074.csv  →  trial_097.csv
epoch_129.csv  →  trial_098.csv
epoch_075.csv  →  trial_099.csv
epoch_076.csv  →  trial_100.csv
epoch_130.csv  →  trial_101.csv
epoch_023.csv  →  trial_102.csv
epoch_077.csv  →  trial_103.csv
epoch_131.csv  →  trial_104.csv
epoch_155.csv  →  trial_105.csv
epoch_101.csv  →  trial_106.csv
epoch_047.csv  →  trial_107.csv
epoch_102.csv  →  trial_108.csv
epoch_156.csv  →  trial_109.csv
epoch_048.csv  →  trial_110.csv
epoch_078.csv  →  trial_111.csv
epoch_024.csv  →  trial_112.csv
epoch_132.csv  →  trial_113.csv
epoch_079.csv  →  trial_114.csv
epoch_025.csv  →  trial_115.csv
epoch_026.csv  →  trial_116.csv
epoch_080.csv  →  trial_117.csv
epoch_133.csv  →  trial_118.csv
epoch_027.csv  →  trial_119.csv
epoch_134.csv  →  trial_120.csv
epoch_135.csv  →  trial_121.csv
epoch_081.csv  →  trial_122.csv
epoch_157.csv  →  trial_123.csv
epoch_049.csv  →  trial_124.csv
epoch_103.csv  →  trial_125.csv
epoch_158.csv  →  trial_126.csv
epoch_050.csv  →  trial_127.csv
epoch_104.csv  →  trial_128.csv
epoch_082.csv  →  trial_129.csv
epoch_028.csv  →  trial_130.csv
epoch_083.csv  →  trial_131.csv

In [6]:
from pathlib import Path
import pandas as pd
import sys, re

# ── EDIT these if you ever move the files ────────────────────────────
MAPPING_TSV = (
    r"C:\Users\cdd\Documents\Uni\Special_course"
    r"\trial_order_eeg.tsv_with_epoch_skip.tsv"
)
PUPIL_ROOT = (
    r"C:\Users\cdd\Documents\Uni\Special_course\pupil_processed_clara"
)
# ─────────────────────────────────────────────────────────────────────

TMP_PATTERN = "__tmp_old{old:03d}_new{new:03d}.csv"

def rename_pupil_epochs(subject: str) -> None:
    """Rename pupil epoch_###.csv → trial_###.csv for one subject."""
    subj = subject if subject.startswith("sub-") else f"sub-{int(subject):03d}"

    # ---------- 1. pull mapping rows for this subject ----------------
    cols = ["subject", "condition", "load",
            "epoch_corrected_skip", "trial_idx"]
    df = (pd.read_csv(MAPPING_TSV, sep="\t", usecols=cols)
            .query("subject == @subj & epoch_corrected_skip.notna()"))

    if df.empty:
        print(f"No mapping rows for {subj}.")
        return

    # ---------- 2. two-phase rename to avoid collisions --------------
    for (cond, load), rows in df.groupby(["condition", "load"]):
        folder = Path(PUPIL_ROOT) / subj / cond / f"{int(load):02d}"
        if not folder.exists():
            print(f"⚠️  Missing folder: {folder}")
            continue

        # Phase A – temp names
        temp_pairs = []           # (tmp_path, final_path) per row
        for r in rows.itertuples(index=False):
            old_no = int(r.epoch_corrected_skip)
            new_no = int(r.trial_idx)

            old_f = folder / f"epoch_{old_no:03d}.csv"
            final_f = folder / f"trial_{new_no:03d}.csv"
            if not old_f.exists():
                print(f"⚠️  missing: {old_f}")
                continue

            tmp_f = folder / TMP_PATTERN.format(old=old_no, new=new_no)
            old_f.rename(tmp_f)
            temp_pairs.append((tmp_f, final_f))

        # Phase B – temp → final
        for tmp_f, final_f in temp_pairs:
            if final_f.exists():
                print(f"⚠️  {final_f.name} already exists, keeping temp.")
                continue
            tmp_f.rename(final_f)
            print(f"{tmp_f.name}  →  {final_f.name}")

    print(f"\nFinished renaming pupil files for {subj}.")


# Loop through all subjects from 32 to 99
for sid in range(32, 99):
    # Skip known missing subjects
    if sid in [37, 66, 94]:
        continue
    
    subject = f"sub-{sid:03d}"
    print(f"\nProcessing {subject}...")
    rename_pupil_epochs(subject)
    
print("\nAll subjects processed.")

Processing sub-032...
⚠️  missing: C:\Users\cdd\Documents\Uni\Special_course\pupil_processed_clara\sub-032\control\05\epoch_015.csv
⚠️  missing: C:\Users\cdd\Documents\Uni\Special_course\pupil_processed_clara\sub-032\control\05\epoch_016.csv
__tmp_old000_new001.csv  →  trial_001.csv
__tmp_old001_new016.csv  →  trial_016.csv
__tmp_old002_new018.csv  →  trial_018.csv
__tmp_old003_new034.csv  →  trial_034.csv
__tmp_old004_new037.csv  →  trial_037.csv
__tmp_old005_new053.csv  →  trial_053.csv
__tmp_old006_new069.csv  →  trial_069.csv
__tmp_old007_new072.csv  →  trial_072.csv
__tmp_old008_new088.csv  →  trial_088.csv
__tmp_old009_new092.csv  →  trial_092.csv
__tmp_old010_new106.csv  →  trial_106.csv
__tmp_old011_new109.csv  →  trial_109.csv
__tmp_old012_new123.csv  →  trial_123.csv
__tmp_old013_new127.csv  →  trial_127.csv
__tmp_old014_new142.csv  →  trial_142.csv
⚠️  missing: C:\Users\cdd\Documents\Uni\Special_course\pupil_processed_clara\sub-032\control\09\epoch_014.csv
⚠️  missing: C:\Users\cdd\Documents\Uni\Special_course\pupil_processed_clara\sub-032\control\09\epoch_015.csv
__tmp_old000_new002.csv  →  trial_002.csv
__tmp_old001_new015.csv  →  trial_015.csv
__tmp_old002_new035.csv  →  trial_035.csv
__tmp_old003_new036.csv  →  trial_036.csv
__tmp_old004_new051.csv  →  trial_051.csv
__tmp_old005_new055.csv  →  trial_055.csv
__tmp_old006_new071.csv  →  trial_071.csv
__tmp_old007_new073.csv  →  trial_073.csv
__tmp_old008_new089.csv  →  trial_089.csv
__tmp_old009_new091.csv  →  trial_091.csv
__tmp_old010_new108.csv  →  trial_108.csv
__tmp_old011_new125.csv  →  trial_125.csv
__tmp_old012_new128.csv  →  trial_128.csv
__tmp_old013_new143.csv  →  trial_143.csv
⚠️  missing: C:\Users\cdd\Documents\Uni\Special_course\pupil_processed_clara\sub-032\control\13\epoch_015.csv
⚠️  missing: C:\Users\cdd\Documents\Uni\Special_course\pupil_processed_clara\sub-032\control\13\epoch_016.csv
__tmp_old000_new000.csv  →  trial_000.csv
__tmp_old001_new017.csv  →  trial_017.csv
__tmp_old002_new020.csv  →  trial_020.csv
__tmp_old003_new033.csv  →  trial_033.csv
__tmp_old004_new038.csv  →  trial_038.csv
__tmp_old005_new052.csv  →  trial_052.csv
__tmp_old006_new070.csv  →  trial_070.csv
__tmp_old007_new074.csv  →  trial_074.csv
__tmp_old008_new087.csv  →  trial_087.csv
__tmp_old009_new090.csv  →  trial_090.csv
__tmp_old010_new105.csv  →  trial_105.csv
__tmp_old011_new110.csv  →  trial_110.csv
__tmp_old012_new124.csv  →  trial_124.csv
__tmp_old013_new126.csv  →  trial_126.csv
__tmp_old014_new141.csv  →  trial_141.csv
⚠️  missing: C:\Users\cdd\Documents\Uni\Special_course\pupil_processed_clara\sub-032\memory\05\epoch_032.csv
⚠️  missing: C:\Users\cdd\Documents\Uni\Special_course\pupil_processed_clara\sub-032\memory\05\epoch_033.csv
⚠️  missing: C:\Users\cdd\Documents\Uni\Special_course\pupil_processed_clara\sub-032\memory\05\epoch_034.csv
⚠️  missing: C:\Users\cdd\Documents\Uni\Special_course\pupil_processed_clara\sub-032\memory\05\epoch_035.csv
__tmp_old000_new003.csv  →  trial_003.csv
__tmp_old001_new006.csv  →  trial_006.csv
__tmp_old002_new009.csv  →  trial_009.csv
__tmp_old003_new014.csv  →  trial_014.csv
__tmp_old004_new022.csv  →  trial_022.csv
__tmp_old005_new029.csv  →  trial_029.csv
__tmp_old006_new031.csv  →  trial_031.csv
__tmp_old007_new032.csv  →  trial_032.csv
__tmp_old008_new042.csv  →  trial_042.csv
__tmp_old009_new045.csv  →  trial_045.csv
__tmp_old010_new046.csv  →  trial_046.csv
__tmp_old011_new047.csv  →  trial_047.csv
__tmp_old012_new058.csv  →  trial_058.csv
__tmp_old013_new064.csv  →  trial_064.csv
__tmp_old014_new066.csv  →  trial_066.csv
__tmp_old015_new068.csv  →  trial_068.csv
__tmp_old016_new075.csv  →  trial_075.csv
__tmp_old017_new076.csv  →  trial_076.csv
__tmp_old018_new078.csv  →  trial_078.csv
__tmp_old019_new085.csv  →  trial_085.csv
__tmp_old020_new095.csv  →  trial_095.csv
__tmp_old021_new097.csv  →  trial_097.csv
__tmp_old022_new100.csv  →  trial_100.csv
__tmp_old023_new103.csv  →  trial_103.csv
__tmp_old024_new112.csv  →  trial_112.csv
__tmp_old025_new113.csv  →  trial_113.csv
__tmp_old026_new117.csv  →  trial_117.csv
__tmp_old027_new118.csv  →  trial_118.csv
__tmp_old028_new129.csv  →  trial_129.csv
__tmp_old029_new130.csv  →  trial_130.csv
__tmp_old030_new132.csv  →  trial_132.csv
__tmp_old031_new137.csv  →  trial_137.csv
⚠️  missing: C:\Users\cdd\Documents\Uni\Special_course\pupil_processed_clara\sub-032\memory\09\epoch_032.csv
⚠️  missing: C:\Users\cdd\Documents\Uni\Special_course\pupil_processed_clara\sub-032\memory\09\epoch_033.csv
⚠️  missing: C:\Users\cdd\Documents\Uni\Special_course\pupil_processed_clara\sub-032\memory\09\epoch_034.csv
⚠️  missing: C:\Users\cdd\Documents\Uni\Special_course\pupil_processed_clara\sub-032\memory\09\epoch_035.csv
__tmp_old000_new004.csv  →  trial_004.csv
__tmp_old001_new007.csv  →  trial_007.csv
__tmp_old002_new008.csv  →  trial_008.csv
__tmp_old003_new013.csv  →  trial_013.csv
__tmp_old004_new021.csv  →  trial_021.csv
__tmp_old005_new026.csv  →  trial_026.csv
__tmp_old006_new028.csv  →  trial_028.csv
__tmp_old007_new030.csv  →  trial_030.csv
__tmp_old008_new039.csv  →  trial_039.csv
__tmp_old009_new040.csv  →  trial_040.csv
__tmp_old010_new041.csv  →  trial_041.csv
__tmp_old011_new049.csv  →  trial_049.csv
__tmp_old012_new059.csv  →  trial_059.csv
__tmp_old013_new061.csv  →  trial_061.csv
__tmp_old014_new062.csv  →  trial_062.csv
__tmp_old015_new063.csv  →  trial_063.csv
__tmp_old016_new079.csv  →  trial_079.csv
__tmp_old017_new080.csv  →  trial_080.csv
__tmp_old018_new081.csv  →  trial_081.csv
__tmp_old019_new084.csv  →  trial_084.csv
__tmp_old020_new099.csv  →  trial_099.csv
__tmp_old021_new101.csv  →  trial_101.csv
__tmp_old022_new102.csv  →  trial_102.csv
__tmp_old023_new104.csv  →  trial_104.csv
__tmp_old024_new115.csv  →  trial_115.csv
__tmp_old025_new116.csv  →  trial_116.csv
__tmp_old026_new119.csv  →  trial_119.csv
__tmp_old027_new122.csv  →  trial_122.csv
__tmp_old028_new133.csv  →  trial_133.csv
__tmp_old029_new134.csv  →  trial_134.csv
__tmp_old030_new136.csv  →  trial_136.csv
__tmp_old031_new138.csv  →  trial_138.csv
⚠️  missing: C:\Users\cdd\Documents\Uni\Special_course\pupil_processed_clara\sub-032\memory\13\epoch_031.csv
⚠️  missing: C:\Users\cdd\Documents\Uni\Special_course\pupil_processed_clara\sub-032\memory\13\epoch_032.csv
⚠️  missing: C:\Users\cdd\Documents\Uni\Special_course\pupil_processed_clara\sub-032\memory\13\epoch_033.csv
⚠️  missing: C:\Users\cdd\Documents\Uni\Special_course\pupil_processed_clara\sub-032\memory\13\epoch_034.csv
__tmp_old000_new005.csv  →  trial_005.csv
__tmp_old001_new010.csv  →  trial_010.csv
__tmp_old002_new011.csv  →  trial_011.csv
__tmp_old003_new012.csv  →  trial_012.csv
__tmp_old004_new023.csv  →  trial_023.csv
__tmp_old005_new024.csv  →  trial_024.csv
__tmp_old006_new025.csv  →  trial_025.csv
__tmp_old007_new027.csv  →  trial_027.csv
__tmp_old008_new043.csv  →  trial_043.csv
__tmp_old009_new044.csv  →  trial_044.csv
__tmp_old010_new048.csv  →  trial_048.csv
__tmp_old011_new050.csv  →  trial_050.csv
__tmp_old012_new057.csv  →  trial_057.csv
__tmp_old013_new060.csv  →  trial_060.csv
__tmp_old014_new065.csv  →  trial_065.csv
__tmp_old015_new067.csv  →  trial_067.csv
__tmp_old016_new077.csv  →  trial_077.csv
__tmp_old017_new082.csv  →  trial_082.csv
__tmp_old018_new083.csv  →  trial_083.csv
__tmp_old019_new086.csv  →  trial_086.csv
__tmp_old020_new094.csv  →  trial_094.csv
__tmp_old021_new096.csv  →  trial_096.csv
__tmp_old022_new098.csv  →  trial_098.csv
__tmp_old023_new111.csv  →  trial_111.csv
__tmp_old024_new114.csv  →  trial_114.csv
__tmp_old025_new120.csv  →  trial_120.csv
__tmp_old026_new121.csv  →  trial_121.csv
__tmp_old027_new131.csv  →  trial_131.csv
__tmp_old028_new135.csv  →  trial_135.csv
__tmp_old029_new139.csv  →  trial_139.csv
__tmp_old030_new140.csv  →  trial_140.csv

Finished renaming pupil files for sub-032.

Processing sub-033...
__tmp_old000_new000.csv  →  trial_000.csv
__tmp_old001_new017.csv  →  trial_017.csv
__tmp_old002_new018.csv  →  trial_018.csv
__tmp_old003_new034.csv  →  trial_034.csv
__tmp_old004_new037.csv  →  trial_037.csv
__tmp_old005_new052.csv  →  trial_052.csv
__tmp_old006_new056.csv  →  trial_056.csv
__tmp_old007_new069.csv  →  trial_069.csv
__tmp_old008_new072.csv  →  trial_072.csv
__tmp_old009_new089.csv  →  trial_089.csv
__tmp_old010_new091.csv  →  trial_091.csv
__tmp_old011_new107.csv  →  trial_107.csv
__tmp_old012_new110.csv  →  trial_110.csv
__tmp_old013_new125.csv  →  trial_125.csv
__tmp_old014_new128.csv  →  trial_128.csv
__tmp_old015_new142.csv  →  trial_142.csv
__tmp_old016_new145.csv  →  trial_145.csv
__tmp_old017_new160.csv  →  trial_160.csv
__tmp_old000_new002.csv  →  trial_002.csv
__tmp_old001_new015.csv  →  trial_015.csv
__tmp_old002_new020.csv  →  trial_020.csv
__tmp_old003_new033.csv  →  trial_033.csv
__tmp_old004_new038.csv  →  trial_038.csv
__tmp_old005_new053.csv  →  trial_053.csv
__tmp_old006_new054.csv  →  trial_054.csv
__tmp_old007_new070.csv  →  trial_070.csv
__tmp_old008_new074.csv  →  trial_074.csv
__tmp_old009_new087.csv  →  trial_087.csv
__tmp_old010_new090.csv  →  trial_090.csv
__tmp_old011_new106.csv  →  trial_106.csv
__tmp_old012_new108.csv  →  trial_108.csv
__tmp_old013_new123.csv  →  trial_123.csv
__tmp_old014_new126.csv  →  trial_126.csv
__tmp_old015_new143.csv  →  trial_143.csv
__tmp_old016_new144.csv  →  trial_144.csv
__tmp_old017_new159.csv  →  trial_159.csv
__tmp_old000_new001.csv  →  trial_001.csv
__tmp_old001_new016.csv  →  trial_016.csv
__tmp_old002_new019.csv  →  trial_019.csv
__tmp_old003_new035.csv  →  trial_035.csv
__tmp_old004_new036.csv  →  trial_036.csv
__tmp_old005_new051.csv  →  trial_051.csv
__tmp_old006_new055.csv  →  trial_055.csv
__tmp_old007_new071.csv  →  trial_071.csv
__tmp_old008_new073.csv  →  trial_073.csv
__tmp_old009_new088.csv  →  trial_088.csv
__tmp_old010_new092.csv  →  trial_092.csv
__tmp_old011_new105.csv  →  trial_105.csv
__tmp_old012_new109.csv  →  trial_109.csv
__tmp_old013_new124.csv  →  trial_124.csv
__tmp_old014_new127.csv  →  trial_127.csv
__tmp_old015_new141.csv  →  trial_141.csv
__tmp_old016_new146.csv  →  trial_146.csv
__tmp_old017_new161.csv  →  trial_161.csv
__tmp_old000_new004.csv  →  trial_004.csv
__tmp_old001_new010.csv  →  trial_010.csv
__tmp_old002_new012.csv  →  trial_012.csv
__tmp_old003_new013.csv  →  trial_013.csv
__tmp_old004_new027.csv  →  trial_027.csv
__tmp_old005_new028.csv  →  trial_028.csv
__tmp_old006_new029.csv  →  trial_029.csv
__tmp_old007_new030.csv  →  trial_030.csv
__tmp_old008_new046.csv  →  trial_046.csv
__tmp_old009_new047.csv  →  trial_047.csv
__tmp_old010_new050.csv  →  trial_050.csv
__tmp_old011_new058.csv  →  trial_058.csv
__tmp_old012_new059.csv  →  trial_059.csv
__tmp_old013_new061.csv  →  trial_061.csv
__tmp_old014_new066.csv  →  trial_066.csv
__tmp_old015_new077.csv  →  trial_077.csv
__tmp_old016_new079.csv  →  trial_079.csv
__tmp_old017_new082.csv  →  trial_082.csv
__tmp_old018_new084.csv  →  trial_084.csv
__tmp_old019_new094.csv  →  trial_094.csv
__tmp_old020_new095.csv  →  trial_095.csv
__tmp_old021_new100.csv  →  trial_100.csv
__tmp_old022_new103.csv  →  trial_103.csv
__tmp_old023_new112.csv  →  trial_112.csv
__tmp_old024_new118.csv  →  trial_118.csv
__tmp_old025_new120.csv  →  trial_120.csv
__tmp_old026_new121.csv  →  trial_121.csv
__tmp_old027_new132.csv  →  trial_132.csv
__tmp_old028_new134.csv  →  trial_134.csv
__tmp_old029_new136.csv  →  trial_136.csv
__tmp_old030_new137.csv  →  trial_137.csv
__tmp_old031_new152.csv  →  trial_152.csv
__tmp_old032_new153.csv  →  trial_153.csv
__tmp_old033_new155.csv  →  trial_155.csv
__tmp_old034_new156.csv  →  trial_156.csv
__tmp_old000_new005.csv  →  trial_005.csv
__tmp_old001_new008.csv  →  trial_008.csv
__tmp_old002_new009.csv  →  trial_009.csv
__tmp_old003_new011.csv  →  trial_011.csv
__tmp_old004_new023.csv  →  trial_023.csv
__tmp_old005_new024.csv  →  trial_024.csv
__tmp_old006_new025.csv  →  trial_025.csv
__tmp_old007_new041.csv  →  trial_041.csv
__tmp_old008_new043.csv  →  trial_043.csv
__tmp_old009_new045.csv  →  trial_045.csv
__tmp_old010_new048.csv  →  trial_048.csv
__tmp_old011_new060.csv  →  trial_060.csv
__tmp_old012_new065.csv  →  trial_065.csv
__tmp_old013_new067.csv  →  trial_067.csv
__tmp_old014_new068.csv  →  trial_068.csv
__tmp_old015_new075.csv  →  trial_075.csv
__tmp_old016_new078.csv  →  trial_078.csv
__tmp_old017_new080.csv  →  trial_080.csv
__tmp_old018_new086.csv  →  trial_086.csv
__tmp_old019_new097.csv  →  trial_097.csv
__tmp_old020_new101.csv  →  trial_101.csv
__tmp_old021_new102.csv  →  trial_102.csv
__tmp_old022_new104.csv  →  trial_104.csv
__tmp_old023_new111.csv  →  trial_111.csv
__tmp_old024_new116.csv  →  trial_116.csv
__tmp_old025_new117.csv  →  trial_117.csv
__tmp_old026_new119.csv  →  trial_119.csv
__tmp_old027_new129.csv  →  trial_129.csv
__tmp_old028_new131.csv  →  trial_131.csv
__tmp_old029_new133.csv  →  trial_133.csv
__tmp_old030_new138.csv  →  trial_138.csv
__tmp_old031_new147.csv  →  trial_147.csv
__tmp_old032_new148.csv  →  trial_148.csv
__tmp_old033_new151.csv  →  trial_151.csv
__tmp_old034_new158.csv  →  trial_158.csv
__tmp_old000_new003.csv  →  trial_003.csv
__tmp_old001_new006.csv  →  trial_006.csv
__tmp_old002_new007.csv  →  trial_007.csv
__tmp_old003_new014.csv  →  trial_014.csv
__tmp_old004_new021.csv  →  trial_021.csv
__tmp_old005_new026.csv  →  trial_026.csv
__tmp_old006_new031.csv  →  trial_031.csv
__tmp_old007_new032.csv  →  trial_032.csv
__tmp_old008_new039.csv  →  trial_039.csv
__tmp_old009_new040.csv  →  trial_040.csv
__tmp_old010_new044.csv  →  trial_044.csv
__tmp_old011_new049.csv  →  trial_049.csv
__tmp_old012_new057.csv  →  trial_057.csv
__tmp_old013_new062.csv  →  trial_062.csv
__tmp_old014_new063.csv  →  trial_063.csv
__tmp_old015_new064.csv  →  trial_064.csv
__tmp_old016_new076.csv  →  trial_076.csv
__tmp_old017_new081.csv  →  trial_081.csv
__tmp_old018_new083.csv  →  trial_083.csv
__tmp_old019_new085.csv  →  trial_085.csv
__tmp_old020_new093.csv  →  trial_093.csv
__tmp_old021_new096.csv  →  trial_096.csv
__tmp_old022_new098.csv  →  trial_098.csv
__tmp_old023_new099.csv  →  trial_099.csv
__tmp_old024_new113.csv  →  trial_113.csv
__tmp_old025_new114.csv  →  trial_114.csv
__tmp_old026_new115.csv  →  trial_115.csv
__tmp_old027_new122.csv  →  trial_122.csv
__tmp_old028_new130.csv  →  trial_130.csv
__tmp_old029_new135.csv  →  trial_135.csv
__tmp_old030_new139.csv  →  trial_139.csv
__tmp_old031_new140.csv  →  trial_140.csv
__tmp_old032_new149.csv  →  trial_149.csv
__tmp_old033_new150.csv  →  trial_150.csv
__tmp_old034_new154.csv  →  trial_154.csv
__tmp_old035_new157.csv  →  trial_157.csv

Finished renaming pupil files for sub-033.

Processing sub-034...
__tmp_old000_new002.csv  →  trial_002.csv
__tmp_old001_new017.csv  →  trial_017.csv
__tmp_old002_new020.csv  →  trial_020.csv
__tmp_old003_new038.csv  →  trial_038.csv
__tmp_old004_new053.csv  →  trial_053.csv
__tmp_old005_new070.csv  →  trial_070.csv
__tmp_old006_new073.csv  →  trial_073.csv
__tmp_old007_new090.csv  →  trial_090.csv
__tmp_old008_new105.csv  →  trial_105.csv
__tmp_old009_new108.csv  →  trial_108.csv
__tmp_old010_new123.csv  →  trial_123.csv
__tmp_old011_new127.csv  →  trial_127.csv
__tmp_old012_new143.csv  →  trial_143.csv
__tmp_old013_new146.csv  →  trial_146.csv
__tmp_old014_new161.csv  →  trial_161.csv
__tmp_old000_new000.csv  →  trial_000.csv
__tmp_old001_new016.csv  →  trial_016.csv
__tmp_old002_new019.csv  →  trial_019.csv
__tmp_old003_new034.csv  →  trial_034.csv
__tmp_old004_new036.csv  →  trial_036.csv
__tmp_old005_new055.csv  →  trial_055.csv
__tmp_old006_new071.csv  →  trial_071.csv
__tmp_old007_new074.csv  →  trial_074.csv
__tmp_old008_new087.csv  →  trial_087.csv
__tmp_old009_new092.csv  →  trial_092.csv
__tmp_old010_new106.csv  →  trial_106.csv
__tmp_old011_new110.csv  →  trial_110.csv
__tmp_old012_new126.csv  →  trial_126.csv
__tmp_old013_new144.csv  →  trial_144.csv
__tmp_old000_new001.csv  →  trial_001.csv
__tmp_old001_new015.csv  →  trial_015.csv
__tmp_old002_new018.csv  →  trial_018.csv
__tmp_old003_new033.csv  →  trial_033.csv
__tmp_old004_new037.csv  →  trial_037.csv
__tmp_old005_new051.csv  →  trial_051.csv
__tmp_old006_new056.csv  →  trial_056.csv
__tmp_old007_new069.csv  →  trial_069.csv
__tmp_old008_new072.csv  →  trial_072.csv
__tmp_old009_new089.csv  →  trial_089.csv
__tmp_old010_new107.csv  →  trial_107.csv
__tmp_old011_new109.csv  →  trial_109.csv
__tmp_old012_new125.csv  →  trial_125.csv
__tmp_old013_new128.csv  →  trial_128.csv
__tmp_old014_new141.csv  →  trial_141.csv
__tmp_old015_new145.csv  →  trial_145.csv
__tmp_old000_new004.csv  →  trial_004.csv
__tmp_old001_new007.csv  →  trial_007.csv
__tmp_old002_new009.csv  →  trial_009.csv
__tmp_old003_new010.csv  →  trial_010.csv
__tmp_old004_new022.csv  →  trial_022.csv
__tmp_old005_new026.csv  →  trial_026.csv
__tmp_old006_new029.csv  →  trial_029.csv
__tmp_old007_new031.csv  →  trial_031.csv
__tmp_old008_new040.csv  →  trial_040.csv
__tmp_old009_new043.csv  →  trial_043.csv
__tmp_old010_new044.csv  →  trial_044.csv
__tmp_old011_new045.csv  →  trial_045.csv
__tmp_old012_new059.csv  →  trial_059.csv
__tmp_old013_new063.csv  →  trial_063.csv
__tmp_old014_new064.csv  →  trial_064.csv
__tmp_old015_new068.csv  →  trial_068.csv
__tmp_old016_new075.csv  →  trial_075.csv
__tmp_old017_new079.csv  →  trial_079.csv
__tmp_old018_new085.csv  →  trial_085.csv
__tmp_old019_new086.csv  →  trial_086.csv
__tmp_old020_new094.csv  →  trial_094.csv
__tmp_old021_new095.csv  →  trial_095.csv
__tmp_old022_new099.csv  →  trial_099.csv
__tmp_old023_new100.csv  →  trial_100.csv
__tmp_old024_new111.csv  →  trial_111.csv
__tmp_old025_new112.csv  →  trial_112.csv
__tmp_old026_new118.csv  →  trial_118.csv
__tmp_old027_new119.csv  →  trial_119.csv
__tmp_old028_new129.csv  →  trial_129.csv
__tmp_old029_new138.csv  →  trial_138.csv
__tmp_old030_new139.csv  →  trial_139.csv
__tmp_old031_new149.csv  →  trial_149.csv
__tmp_old032_new151.csv  →  trial_151.csv
__tmp_old033_new152.csv  →  trial_152.csv
__tmp_old034_new156.csv  →  trial_156.csv
__tmp_old000_new005.csv  →  trial_005.csv
__tmp_old001_new008.csv  →  trial_008.csv
__tmp_old002_new013.csv  →  trial_013.csv
__tmp_old003_new014.csv  →  trial_014.csv
__tmp_old004_new021.csv  →  trial_021.csv
__tmp_old005_new023.csv  →  trial_023.csv
__tmp_old006_new025.csv  →  trial_025.csv
__tmp_old007_new032.csv  →  trial_032.csv
__tmp_old008_new041.csv  →  trial_041.csv
__tmp_old009_new048.csv  →  trial_048.csv
__tmp_old010_new050.csv  →  trial_050.csv
__tmp_old011_new057.csv  →  trial_057.csv
__tmp_old012_new065.csv  →  trial_065.csv
__tmp_old013_new066.csv  →  trial_066.csv
__tmp_old014_new067.csv  →  trial_067.csv
__tmp_old015_new077.csv  →  trial_077.csv
__tmp_old016_new083.csv  →  trial_083.csv
__tmp_old017_new084.csv  →  trial_084.csv
__tmp_old018_new093.csv  →  trial_093.csv
__tmp_old019_new101.csv  →  trial_101.csv
__tmp_old020_new103.csv  →  trial_103.csv
__tmp_old021_new114.csv  →  trial_114.csv
__tmp_old022_new116.csv  →  trial_116.csv
__tmp_old023_new121.csv  →  trial_121.csv
__tmp_old024_new132.csv  →  trial_132.csv
__tmp_old025_new136.csv  →  trial_136.csv
__tmp_old026_new140.csv  →  trial_140.csv
__tmp_old027_new147.csv  →  trial_147.csv
__tmp_old028_new150.csv  →  trial_150.csv
__tmp_old029_new157.csv  →  trial_157.csv
__tmp_old000_new003.csv  →  trial_003.csv
__tmp_old001_new011.csv  →  trial_011.csv
__tmp_old002_new012.csv  →  trial_012.csv
__tmp_old003_new024.csv  →  trial_024.csv
__tmp_old004_new027.csv  →  trial_027.csv
__tmp_old005_new030.csv  →  trial_030.csv
__tmp_old006_new042.csv  →  trial_042.csv
__tmp_old007_new046.csv  →  trial_046.csv
__tmp_old008_new047.csv  →  trial_047.csv
__tmp_old009_new049.csv  →  trial_049.csv
__tmp_old010_new058.csv  →  trial_058.csv
__tmp_old011_new060.csv  →  trial_060.csv
__tmp_old012_new061.csv  →  trial_061.csv
__tmp_old013_new062.csv  →  trial_062.csv
__tmp_old014_new076.csv  →  trial_076.csv
__tmp_old015_new080.csv  →  trial_080.csv

In [3]:
# match sampling rates if eeg is 250Hz and pupil is 100Hz
from scipy.signal import resample_poly
SUBJECTS = np.setdiff1d(np.arange(32, 99), [33, 34, 37, 66, 94])

FS_IN   = 250        # original sampling rate
FS_OUT  = 100        # target sampling rate
UP      = 2          # polyphase factors  (250 → 100 = 2/5)
DOWN    = 5

EEG_ROOT = Path(r"C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert")


for sub in SUBJECTS:
    sub_tag = f"sub-{sub:03d}"
    eeg_sub = EEG_ROOT / sub_tag
    if not eeg_sub.exists():
        print(f"{sub_tag}: EEG folder missing - skipped")
        continue
    print(f"Processing {sub_tag}...")

    for cond_path in eeg_sub.iterdir():          # memory / control
        for load_path in cond_path.iterdir():    # 05 / 09 / 13
            for trial_file in load_path.glob("trial_*.csv"):
                # Read the EEG epoch file (comma-separated)
                df = pd.read_csv(trial_file, comment="#") 

                time = df.iloc[:, 0].to_numpy(float)        # or df['time'].to_numpy(float)
                eeg  = df.iloc[:, 1:].to_numpy()            # shape: (n_samples, n_channels)

                # ------------------------------------------------------------------
                # 1. resample 250 → 100 Hz with anti-alias
                # ------------------------------------------------------------------
                eeg_ds = resample_poly(eeg, up=UP, down=DOWN, axis=0)

                # resample the time column
                n_out   = eeg_ds.shape[0]
                time_ds = np.arange(n_out) / FS_OUT + time[0]
                time_ds = np.round(time_ds, 2)

                # ------------------------------------------------------------------
                # 2. save back (overwrite or new file)
                # ------------------------------------------------------------------
                df_out = pd.DataFrame(
                    np.column_stack([time_ds, eeg_ds]),
                    columns=df.columns
                )
                df_out.to_csv(trial_file, index=False)
                print(f"Saved {trial_file}  (shape: {df_out.shape})")

Processing sub-032...
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\control\05\trial_001.csv  (shape: (656, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\control\05\trial_016.csv  (shape: (656, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\control\05\trial_018.csv  (shape: (656, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\control\05\trial_034.csv  (shape: (657, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\control\05\trial_037.csv  (shape: (658, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\control\05\trial_053.csv  (shape: (657, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\control\05\trial_056.csv  (shape: (657, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\control\05\trial_069.csv  (shape: (657, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\control\05\trial_072.csv  (shape: (658, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\control\05\trial_088.csv  (shape: (657, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\control\05\trial_092.csv  (shape: (657, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\control\05\trial_106.csv  (shape: (658, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\control\05\trial_109.csv  (shape: (656, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\control\05\trial_123.csv  (shape: (658, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\control\05\trial_127.csv  (shape: (657, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\control\05\trial_142.csv  (shape: (658, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\control\05\trial_146.csv  (shape: (657, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\control\05\trial_159.csv  (shape: (657, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\control\09\trial_002.csv  (shape: (1062, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\control\09\trial_015.csv  (shape: (1062, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\control\09\trial_019.csv  (shape: (1064, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\control\09\trial_035.csv  (shape: (1064, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\control\09\trial_036.csv  (shape: (1064, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\control\09\trial_051.csv  (shape: (1063, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\control\09\trial_055.csv  (shape: (1063, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\control\09\trial_071.csv  (shape: (1065, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\control\09\trial_073.csv  (shape: (1064, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\control\09\trial_089.csv  (shape: (1065, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\control\09\trial_091.csv  (shape: (1065, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\control\09\trial_107.csv  (shape: (1064, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\control\09\trial_108.csv  (shape: (1064, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\control\09\trial_125.csv  (shape: (1064, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\control\09\trial_128.csv  (shape: (1064, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\control\09\trial_143.csv  (shape: (1065, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\control\09\trial_145.csv  (shape: (1065, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\control\09\trial_161.csv  (shape: (1065, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\control\13\trial_000.csv  (shape: (1470, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\control\13\trial_017.csv  (shape: (1464, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\control\13\trial_020.csv  (shape: (1470, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\control\13\trial_033.csv  (shape: (1469, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\control\13\trial_038.csv  (shape: (1470, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\control\13\trial_052.csv  (shape: (1470, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\control\13\trial_054.csv  (shape: (1470, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\control\13\trial_070.csv  (shape: (1470, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\control\13\trial_074.csv  (shape: (1470, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\control\13\trial_087.csv  (shape: (1469, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\control\13\trial_090.csv  (shape: (1472, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\control\13\trial_105.csv  (shape: (1470, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\control\13\trial_110.csv  (shape: (1471, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\control\13\trial_124.csv  (shape: (1472, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\control\13\trial_126.csv  (shape: (1469, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\control\13\trial_141.csv  (shape: (1470, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\control\13\trial_144.csv  (shape: (1472, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\control\13\trial_160.csv  (shape: (1472, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\05\trial_003.csv  (shape: (656, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\05\trial_006.csv  (shape: (657, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\05\trial_009.csv  (shape: (655, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\05\trial_014.csv  (shape: (657, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\05\trial_022.csv  (shape: (658, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\05\trial_029.csv  (shape: (658, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\05\trial_031.csv  (shape: (657, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\05\trial_032.csv  (shape: (657, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\05\trial_042.csv  (shape: (658, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\05\trial_045.csv  (shape: (656, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\05\trial_046.csv  (shape: (658, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\05\trial_047.csv  (shape: (656, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\05\trial_058.csv  (shape: (657, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\05\trial_064.csv  (shape: (657, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\05\trial_066.csv  (shape: (656, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\05\trial_068.csv  (shape: (656, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\05\trial_075.csv  (shape: (658, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\05\trial_076.csv  (shape: (658, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\05\trial_078.csv  (shape: (657, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\05\trial_085.csv  (shape: (658, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\05\trial_095.csv  (shape: (657, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\05\trial_097.csv  (shape: (659, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\05\trial_100.csv  (shape: (657, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\05\trial_103.csv  (shape: (656, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\05\trial_112.csv  (shape: (658, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\05\trial_113.csv  (shape: (658, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\05\trial_117.csv  (shape: (658, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\05\trial_118.csv  (shape: (659, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\05\trial_129.csv  (shape: (657, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\05\trial_130.csv  (shape: (656, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\05\trial_132.csv  (shape: (658, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\05\trial_137.csv  (shape: (656, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\05\trial_148.csv  (shape: (659, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\05\trial_153.csv  (shape: (657, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\05\trial_155.csv  (shape: (656, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\05\trial_156.csv  (shape: (656, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\09\trial_004.csv  (shape: (1063, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\09\trial_007.csv  (shape: (1060, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\09\trial_008.csv  (shape: (1059, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\09\trial_013.csv  (shape: (1060, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\09\trial_021.csv  (shape: (1062, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\09\trial_026.csv  (shape: (1064, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\09\trial_028.csv  (shape: (1063, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\09\trial_030.csv  (shape: (1064, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\09\trial_039.csv  (shape: (1064, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\09\trial_040.csv  (shape: (1065, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\09\trial_041.csv  (shape: (1062, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\09\trial_049.csv  (shape: (1063, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\09\trial_059.csv  (shape: (1065, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\09\trial_061.csv  (shape: (1064, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\09\trial_062.csv  (shape: (1064, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\09\trial_063.csv  (shape: (1064, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\09\trial_079.csv  (shape: (1064, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\09\trial_080.csv  (shape: (1063, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\09\trial_081.csv  (shape: (1065, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\09\trial_084.csv  (shape: (1065, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\09\trial_099.csv  (shape: (1063, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\09\trial_101.csv  (shape: (1065, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\09\trial_102.csv  (shape: (1064, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\09\trial_104.csv  (shape: (1064, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\09\trial_115.csv  (shape: (1065, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\09\trial_116.csv  (shape: (1064, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\09\trial_119.csv  (shape: (1064, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\09\trial_122.csv  (shape: (1064, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\09\trial_133.csv  (shape: (1064, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\09\trial_134.csv  (shape: (1063, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\09\trial_136.csv  (shape: (1062, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\09\trial_138.csv  (shape: (1062, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\09\trial_149.csv  (shape: (1063, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\09\trial_150.csv  (shape: (1063, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\09\trial_152.csv  (shape: (1063, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\09\trial_154.csv  (shape: (1065, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\13\trial_005.csv  (shape: (1464, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\13\trial_010.csv  (shape: (1466, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\13\trial_011.csv  (shape: (1463, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\13\trial_012.csv  (shape: (1465, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\13\trial_023.csv  (shape: (1467, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\13\trial_024.csv  (shape: (1471, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\13\trial_025.csv  (shape: (1467, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\13\trial_027.csv  (shape: (1470, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\13\trial_043.csv  (shape: (1470, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\13\trial_044.csv  (shape: (1471, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\13\trial_048.csv  (shape: (1471, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\13\trial_050.csv  (shape: (1472, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\13\trial_057.csv  (shape: (1472, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\13\trial_060.csv  (shape: (1469, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\13\trial_065.csv  (shape: (1470, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\13\trial_067.csv  (shape: (1470, 18))
Saved C:\Users\cdd\Documents\Uni\Special_course\code\Special_course\eeg_theta_hilbert\sub-032\memory\13\trial_077.csv  (shape: (1470, 18))